### ISSUE TITLE
Upgrade to HAOS 2023.8 breaks matrix-nio (missing requirements)

### ISSUE THREAD

**Issue by FeLLa-23** [PaarthShah/matrix-nio-hacs#17]
## System Information

version | core-2023.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1283
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 62.3 GB
disk_used | 34.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | redacted

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 10
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 24, 2023 at 21:28
-- | --
current_recorder_run | August 3, 2023 at 21:32
estimated_db_size | 4206.23 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/PaarthShah/matrix-nio-hacs/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, first of all, thanks for creating the hacs-repo! I used your matrix-nio-hacs integrations since the first day without any problems. Since the upgrade to Home-Assistant 2023.8. the integration isn't longer working because of missing requirments.

### Reproduction steps

1. Upgrading Home-Assistant core from version 2023.7.3 to 2023.8.
2. Trying to restart Home-Assistant results in the error showing below.

### Debug logs

```text
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:568
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 21:43:48 (1 occurrences)
Last logged: 21:43:48

The system cannot restart because the configuration is not valid: Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Integration error: matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
	




Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:579
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:43:48 (1 occurrences)
Last logged: 21:43:48

[140465551150144] The system cannot restart because the configuration is not valid: Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0']. Integration error: matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 579, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
Platform error notify.matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
Integration error: matrix - Requirements for matrix not found: ['Pillow==9.5.0'].
```

**Comment by FeLLa-23** [comment]
Issue can be closed because its fixed by version 1.0.3 (https://github.com/PaarthShah/matrix-nio-hacs/pull/18)

Thanks! :)
